READ DOCUMENT https://numpy.org/devdocs/user/absolute_beginners.html



In [196]:
import numpy as np

In [197]:
a= np.array([1,2,3,4,5], dtype='int16')
print(a)

[1 2 3 4 5]


In [198]:
b= np.array([[7,3,5,5,3],[1,4,6,3,6]])
print(b)

[[7 3 5 5 3]
 [1 4 6 3 6]]


In [199]:
# Get dimensions
a.ndim
b.ndim


2

In [200]:
# Get shape
b.shape

(2, 5)

In [201]:
# Get type
a.dtype

dtype('int16')

In [202]:
# Get size
a.itemsize

2

In [203]:
#Get total size
a.size

5

In [204]:
# ACCESSING OR CHANGING SPECIFIC ELEMENTS, ROWS, COLUMNS ETC.

In [205]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [206]:
# Get a specified element
a[1,5]

13

In [207]:
# Get sepcific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [208]:
# Get specific column
a[:,0]

array([1, 8])

In [209]:
# Getting a little fancy [startingindex:endingindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [210]:
a[1,5]=90
print (a)

a[:,2]=99
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 90 14]]
[[ 1  2 99  4  5  6  7]
 [ 8  9 99 11 12 90 14]]


In [211]:
# 3D EXAMPLES

b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [212]:
# Get Specified element 
b[0,0,1]

2

In [213]:
# Replace
b[:,1,:]=99
# b[:,1,:]=[[9,9],[10,10]]
print(b)

[[[ 1  2]
  [99 99]]

 [[ 5  6]
  [99 99]]]


In [214]:
# INITIALIZING DIFFERENT TYPES OF ARRAYS


In [215]:
# All 0's matrix
np.zeros((4,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [216]:
# All 1's Matrix
np.ones((2,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [217]:
# Any other number matrix
np.full((2,4,2),99) 

array([[[99, 99],
        [99, 99],
        [99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99],
        [99, 99],
        [99, 99]]])

In [218]:
# Any other number (full_like)
print(a)
print(np.full_like(a,4))


[[ 1  2 99  4  5  6  7]
 [ 8  9 99 11 12 90 14]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [219]:
# Random decimal numbers
np.random.rand(4,3)

np.random.random_sample(a.shape)

array([[0.40643261, 0.8421246 , 0.3616512 , 0.5732394 , 0.55046463,
        0.80859637, 0.60554948],
       [0.66289678, 0.12357497, 0.66751389, 0.83068899, 0.8779353 ,
        0.54145341, 0.22312776]])

In [220]:
# Random integer values 
# SYNTAX=np.random.randint(MAX-NUMBER, size=(rows,column))
np.random.randint(7, size=(4,5))

# np.random.randint(MIN-NUMBER,MAX-NUMBER, size=(rows,column))
np.random.randint(5,7, size=(4,5))

array([[6, 5, 6, 5, 6],
       [6, 5, 6, 6, 6],
       [5, 5, 5, 6, 5],
       [5, 6, 5, 6, 6]])

In [221]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [222]:
# Repeating an array
arr= np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [223]:
Expl=np.zeros((5,5))

Expl[2,2]=9
Expl[:,0]=1
Expl[0,:]=1
Expl[-1,:]=1
Expl[:,-1]=1


print(Expl)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [224]:
# #BE CAREFULL WHILE COPYING ARRAYS
a =np.array([1,2,3])
b=a
b[1]=999

print(a)
print(b)
# Both the arrays get updated .Equating two arrays means they both are pointing on the same 


[  1 999   3]
[  1 999   3]


In [225]:
# MATHEMATICS------------

In [226]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [227]:
a+2

array([3, 4, 5, 6])

In [228]:
a-2

array([-1,  0,  1,  2])

In [229]:
a*2

array([2, 4, 6, 8])

In [230]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [231]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [232]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [233]:
a**2

array([ 1,  4,  9, 16])

In [234]:
# Take sin value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [235]:
a= np.ones((2,4))
print(a)
b= np.full((4,5),2)
print(b)

np.matmul(a,b)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [236]:
# Find determinant

c= np.identity(3)
np.linalg.det(c)

# And inverse, trace, singular vector decomposition, matrix norms etc. can be found very easily.

1.0

In [237]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [238]:
np.min(stats,axis=1)
# axis=1 means rows mai se minimum
# axis=2 means columns mai se minimum


array([1, 4])

In [239]:
np.max(stats)

6

In [240]:
np.sum(stats)

21

Recognizing Arrays


In [241]:
before= np.array([[0,1,2,3],[4,5,6,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[0 1 2 3]
 [4 5 6 8]]
[[0 1]
 [2 3]
 [4 5]
 [6 8]]


In [242]:
# Vertical stacking vectors
v1= np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [243]:
h1 = np.array([1,2,3,4])
h2 = np.array([4,5,3,4])

np.hstack((h1,h2))

array([1, 2, 3, 4, 4, 5, 3, 4])